import Foundation

class ModelWords {
    static let prettyWords: [String: String] = ["abattoir " : "a slaughterhouse; massacre",
                                                "absinthe " : "wormwood liquor of a bright-green color",
                                                "acciaccatura " : "grace note, an embellishing note usually written in smaller size",
                                                "acedia " : "ennui; state of torpor or listlessness; spiritual apathy",
                                                "acervuline " : "aggregated, heaped up, bundled, collected or localized",
                                                "acidulous " : "somewhat acidic or sour in taste or manner; somewhat sarcastic",
                                                "acolyte " : "ranked clergy member; assistant in liturgical rites",
                                                "acoustic " : "of or relating to sound, the sense of hearing, or the science of sound",
                                                "acquiesce " : "to passively accept; to accept, comply, or submit passively",
                                                "adroit " : "quick or skillful; adept in action or thought",
                                                "adumbrate " : "to explain faintly or opaquely outline; describe",
                                                "aeipathy " : "continued passion; unyielding disease",
                                                "aeneous " : "brassy; a type of golden-green",
                                                "aeolian " : "pertaining to, of, related to, caused by or like the wind or aeolus",
                                                "aeonian " : "continuing forever; eternal",
                                                "aerial " : "of, in, or caused by the air; existing or living in the air",
                                                "aesthete " : "person who appreciates art or beauty",
                                                "aestival " : "pertaining to, relating, designating, or of summer",
                                                "aeviternal " : "eternal, endless, never-ending",
                                                "afflatus " : "strong creative impulse, especially as a result of divine inspiration; inspiration",
                                                "aileron " : "small moveable platforms on the back of plane wings that alter air movements",
                                                "ailurophile " : "cat-lover, one who loves or appreciates cats",
                                                "alabaster " : "dense translucent, white or tinted, fine-grained gypsum",
                                                "alienate " : "to estrange; to cause to become unfriendly or hostile",
                                                "aliment " : "something that nourishes; food; to supply with sustenance or food",
                                                "allegretto " : "music term, moderately fast tempo",
                                                "alleviate " : "to allay; to lessen in pain or negative occurrence or consequence",
                                                "alloquy " : "speaking to another; an address",
                                                "allure " : "attraction; temptation; to attract with something desirable",
                                                "alluvium " : "unconsolidated sediments carried by water",
                                                "amaranth " : "deep-hued purple; a type of purple flower; used as a metaphor for immortality",
                                                "amber " : "light brown; light yellow",
                                                "ambience " : "atmosphere; a particular environment or surrounding influence; aura",
                                                "ambivalence " : "simultaneous, conflicted feelings towards a thing, person, etc.",
                                                "ambrosia " : "the food of the gods; something overpoweringly delicious or fragrant",
                                                "ameliorate " : "to make better; improve, enhance",
                                                "amelus " : "individual exhibiting amelia (the congenital absence of one or more limbs)",
                                                "amethyst " : "deep purple; deep-purple gemstone",
                                                "amnesia " : "partial or total loss of memory",
                                                "amphisbaena " : "greek mythological being, a two-headed snake with a head on each end",
                                                "amphora " : "ceramic, two-handled vase with a narrow neck, usually containing alcohol",
                                                "amulet " : "a charm against evil or impurity, often a piece of jewelry",
                                                "analemma " : "sundial, figure-8 indicating sun’s position",
                                                "ancestry " : "the inception or origin of a phenomenon, object, idea, or style; lineage",
                                                "andante " : "music, moderately slow",
                                                "anemone " : "a flowery marine creature",
                                                "antebellum " : "before or existing before a war, especially the american civil war",
                                                "anxiolytic " : "preventing or reducing anxiety; antianxiety medication; tranquilizer",
                                                "aperitif " : "alcoholic drink taken as an appetizer before a meal",
                                                "aphelion " : "point indicated when the orbit of the earth is furthest from the sun",
                                                "aphesis " : "omission of sound or verbiage at the beginning of a word or phrase",
                                                "aphotic " : "devoid of light, especially of areas where no light naturally occurs",
                                                "apocope " : "omission of sound or verbiage at the end of a word or phrase",
                                                "apophenia " : "the perception of or belief in connectedness among unrelated phenomena",
                                                "apoplexy " : "stroke; impairment or neuralgia from cerebral hemorrhage",
                                                "aposiopesis " : "abrupt stop of a thought in a sentence, as if the speaker could not continue",
                                                "apostasy " : "abandonment of one's religious faith, political party, one's principles, or a cause",
                                                "apostolicity " : "being of or contemporary with the apostles in character",
                                                "apotheosis " : "deification; quintessence; exaltation to divine rank or stature",
                                                "apropos " : "appropriate of; appropriate",
                                                "aquarelle " : "painting done in transparent watercolors; watercolor; watercolor painting",
                                                "aqueous " : "of, relating to, or resembling water; made from, with, or by water",
                                                "aquiline " : "resembling an eagle’s beak; hooked like a beak",
                                                "arabesque " : "a ballet twirl; type of artistry involving a continuous, rotating design",
                                                "aria " : "air or song; a melody, solo in an opera accompanied by instrumentation",
                                                "artemisia " : "type of plant, genus of aromatic shrubs or herbs",
                                                "ascertain " : "to understand specific facts; to ferret out information",
                                                "ashlar " : "a squared block of building stone and dressed for outward placement",
                                                "asphodel " : "a type of flower, often associated with the underworld",
                                                "astral " : "of or pertaining to the aster; stellar; star-shaped; pertaining to the stars",
                                                "asylum " : "refuge; a place to restore sanity or facilitate recovery",
                                                "atelier " : "an artist’s studio; a place designated to create or perform art",
                                                "athanasy " : "quality of being deathless; immortality",
                                                "athenaeum " : "institution for the promotion of literary or scientific learning; phrontistery",
                                                "aubade " : "poem or song about or evocative dawn or morning, the opposite of nocturne",
                                                "auburn " : "moderate reddish-brown",
                                                "aura " : "distinctive and pervasive quality or character; air; atmosphere; emanation",
                                                "austere " : "severe or stern in disposition, discipline, or appearance; somber and grave",
                                                "autumnal " : "pertaining to, like, relating, or evocative of autumn",
                                                "auxiliary " : "additional, supplementary; reserve; acting as a subsidiary",
                                                "avarice " : "extreme greed for wealth or material gain",
                                                "avenue " : "wide street or thoroughfare; roadway lined with tress",
                                                "azalea " : "type of plant, a common garden plant",
                                                "azoth " : "mythologized universal solvent; panacea",
                                                "azuline " : "light blue; similar to a light blue",
                                                "azure " : "sky-blue or a light blue",
                                                "baccalaureate " : "bachelor’s degree; valedictory speech",
                                                "balustrade " : "architectural term, series of balusters or parapet",
                                                "banderilla " : "a decorated dart that is shot into the neck of the bull during a bull fight",
                                                "bardiglio " : "finely-grained, multi-gray italian marble",
                                                "basilica " : "large, public building the romans used, usually as a courtroom or meeting hall",
                                                "bastille " : "imprisonment, jail, prison",
                                                "bayonet " : "blade adapted to fit the muzzle-end of a rifle and as a weapon in close combat",
                                                "belladonna " : "a type of plant, highly poisonous; “pretty woman”",
                                                "belle-lettres " : "“beautiful letters” aesthetic literature, as opposed to didactic",
                                                "bellicose " : "inclined or eager to fight; aggressively hostile; belligerent; pugnacious",
                                                "bellwether " : "leader or indicator of future trends, trendsetter",
                                                "belvedere " : "roofed structure, on top of another building, which commands a large view",
                                                "berceuse " : "lullaby; song used to put someone to sleep",
                                                "bethesda " : "a hallowed, sanctified, or holy place; a chapel; holy ground",
                                                "bezaleel " : "the shadow of god, god’s shadow",
                                                "bibelot " : "trinket, bauble; small object which is rare or valuable or beautiful; a small book",
                                                "bibliophile " : "someone who loves (and usually collects) books; book collector",
                                                "bijouterie " : "pl. trinkets or jewelry, gallery thereof, display thereof",
                                                "bivouac " : "temporary military or squad encampment",
                                                "blaze " : "bright flame of fire; bright steady light or glare; hot gleam",
                                                "blellum " : "an idle, indiscreet talker; noisy fainéant",
                                                "bliss " : "joy, rapture, elation, felicity",
                                                "blithe " : "carefree, nonchalant; heedless; lacking concern; joyous",
                                                "blossom " : "billowing; period or condition of flowering or growth",
                                                "bloviate " : "to make pompous or arrogant discourse",
                                                "boeotian " : "marked by stupidity and philistinism; crudely obtuse; loutish",
                                                "borasca " : "a squall, usually accompanied by thunder and lightning",
                                                "bordereau " : "a detailed note or memorandum of account",
                                                "boulevard " : "broad street, avenue; broad spectrum of something",
                                                "bouleversement " : "reversal of fortunes; overturning; tumult",
                                                "bourgeoisie " : "the middle class; the middle class in communist theory",
                                                "braggadocio " : "arrogant person; braggart; arrogant or boastful behavior",
                                                "brecciate " : "to form rock into breccia (rocks made of sharp fragments set in a grainy matrix)",
                                                "breeze " : "gentle push of the wind",
                                                "breviloquence " : "speech characterized by brevity; shortness, briefness",
                                                "brevity " : "briefness; swiftness; evanescence",
                                                "bricolage " : "something made or put together using any materials that happen are available",
                                                "brio " : "joie de vivre; vivacity; alacrity; gusto; esprit",
                                                "burnish " : "to polish; the shine of a polished surface",
                                                "caballero " : "skilled horseman; gentleman; cavalier",
                                                "cabaret " : "a restaurant with live entertainment",
                                                "cadence " : "rhythmic flow of the sounds of language; lilt",
                                                "cadenza " : "musical or literary improvisation",
                                                "caesious " : "a type of bluish gray",
                                                "caesura " : "a pause in a line of verse, usually in poetry",
                                                "calico " : "coarse, brightly printed cloth; a type of pattern",
                                                "caliginous " : "misty; dim; obscure; dark; gloomy; tenebrous",
                                                "calliope " : "musical instrument fitted with steam whistles, played from a keyboard",
                                                "callipygian " : "having a beautiful, admirable, or sexy butt",
                                                "callow " : "immature; green, lacking experience; naïve",
                                                "calypso " : "a type of rare orchid; a tribal and fervid dance",
                                                "cancrizans " : "backwards movement; crab walking; music moving backwards",
                                                "candelabra " : "pl. branched candlestick with several candles",
                                                "canticle " : "a song, poem, or hymn, usually of a church choir",
                                                "capriccio " : "music, improvisation, without adherence to rules",
                                                "capriccioso " : "music, lively and free of restraint, restriction, or direction",
                                                "capricious " : "impulsive; whimsical; unpredictable",
                                                "caress " : "touch or stroke lightly in a loving or endearing manner",
                                                "cartesian " : "of or relating to the philosophy of descartes",
                                                "cascarilla " : "west indian shrub with aromatic bark, typically used in incense or tonics",
                                                "catena " : "closely linked series; connected series of related things, especially of writing",
                                                "cathismata " : "pl. one of the 20 divisions in a greek psalter",
                                                "cavil " : "to object or criticize adversely for trivial reasons; flimsy objection or qualm",
                                                "cedilla " : "a diacritic beneath a letter designed to alter pronunciation “façade”",
                                                "celadon " : "a type of pale green",
                                                "celeripedean " : "quick-footed; swift; fast-running",
                                                "celerity " : "speed; alacrity; briskness",
                                                "celesta " : "ancient musical instrument",
                                                "celestial " : "heavenly; of a higher plane; empyreal; pertaining to or of space",
                                                "cello " : "large, stringed instrument that generates deep tones",
                                                "cellophane " : "thin, flexible, transparent cellulose material used as moisture-proof wrapping",
                                                "cellular " : "pertaining to cells or their structure; containing cells",
                                                "cellulite " : "fatty deposit causing a dimpled appearance, as around the thighs or buttocks",
                                                "celluloid " : "transparent, colorless, synthetic plastic used to manufacture photographic film",
                                                "cenotaph " : "an unmarked grave",
                                                "centennial " : "of or relating to a period of 100 years; occurring once every 100 years",
                                                "cerulean " : "a type of watery blue",
                                                "cerumen " : "yellow, wax-like secretion from the external ears; “earwax”",
                                                "cessation " : "pause; interruption; ceasing; ending",
                                                "chalice " : "cup for consecrated wine; goblet",
                                                "chamois " : "goatlike antelope; type of cloth for cleaning",
                                                "champagne " : "a type of bubbling alcohol with fruity taste",
                                                "chandelier " : "ceiling-mounted light fixture or glass structure",
                                                "chantpleure " : "to cry while singing; to cry and sing simultaneously",
                                                "chariot " : "two or four-wheeled, horse-drawn war or procession vehicle",
                                                "chartreuse " : "a type of swampy green",
                                                "chatelaine " : "the mistress or lady of a castle or large household",
                                                "chatoyant " : "like or resembling a cat’s eye",
                                                "chauffer " : "a designated paid driver for formal occasions",
                                                "cheilion " : "the corner of the mouth or oral cavity",
                                                "chevelure " : "head of hair; hair on the head; tresses; a nebulous aura (as around a comet)",
                                                "chiaroscuro " : "composition of strong contrasts in light and dark",
                                                "chiasmus " : "rhetorical term, inverse sentence, “one should eat to live, not live to eat”",
                                                "choreography " : "the art of creating and arranging dances or ballets",
                                                "cicada " : "loud, locust-like insect that chirrups",
                                                "cigány " : "gypsy; hungarian gypsy",
                                                "cinder " : "burned substance, one which is no longer capable of combustion",
                                                "cinnabar " : "bright red; glowing red",
                                                "cinquefoil " : "five-leave; plant with limbs that are five-leaved; five-pointed leaves",
                                                "circlet " : "ring-shaped ornament or piece of jewelry, especially for the head",
                                                "circuitous " : "having a circular or winding course; indirect; roundabout",
                                                "circular " : "of, like, related to, or resembling a circle",
                                                "cislunar " : "of or relating to the space between earth and the moon or the moon’s orbit",
                                                "cistern " : "an underground reservoir",
                                                "citadel " : "bulwark; a fortress or stronghold; refuge",
                                                "cithara " : "ancient greek instrument, like a lyre",
                                                "civility " : "formal or perfunctory politeness; state of being civil",
                                                "clandestine " : "kept secretly or done secretively",
                                                "clarion " : "medieval trumpet with clear shrill tones; clear and shrill; loud burst of sound",
                                                "clavicle " : "the collarbone of a human",
                                                "clavilux " : "an odd machine that generates light to the rhythm of music",
                                                "cleanse " : "to free from dirt, defilement, or guilt; purge or clean",
                                                "clemency " : "mercy; an act of mercy; showing mercy",
                                                "clerisy " : "the well-educated or learned class; intelligentsia; cognoscenti",
                                                "clinquant " : "glittering as gold; glittering with tinsel; showily ornate",
                                                "clithridiate " : "keyhole-shaped; resembling a keyhole",
                                                "cloister " : "monastatic establishment; convent of living",
                                                "coalesce " : "to fuse, intersect, or entwine to create a unity; to unify by an external means",
                                                "coelacanth " : "a type of prehistoric fish, initially thought to be extinct",
                                                "coercion " : "the act of coercing; the use of pressure, threats, blackmail, or intimidation",
                                                "collectanea " : "selection of pieces of writing by an author or by several authors",
                                                "colliquate " : "to change from solid to liquid; to liquefy",
                                                "colloquial " : "informal, as in speech; conversationally informal",
                                                "colophon " : "inscription at the end of a book; an identifying emblem for a book",
                                                "coloratura " : "elaborate or technical vocal music with florid ornamentation",
                                                "comestibles " : "items suitable to be eaten; edible sundries; articles of food; victuals",
                                                "communiqué " : "an official announcement; bulletin board; a dispatch; an official report",
                                                "conciliabule " : "secret meeting of conspirators",
                                                "conciliate " : "to win over from a state of hostility or distrust; appease",
                                                "concinnity " : "harmony in the arrangement or fitness of parts with respect to a whole",
                                                "concupiscence " : "lasciviousness; lewdness; ardent lust",
                                                "congelifraction " : "splitting or disintegration of rocks as a result of the freezing of the water",
                                                "constellation " : "specific arrangement of stars to form an image",
                                                "convalesce " : "to recover or recuperate; recover from a serious injury",
                                                "copse " : "thicket of small trees or shrubs; a coppice; small wood; a tree",
                                                "coquelicot " : "a type of plant, red poppy",
                                                "coquette " : "woman who makes teasing sexual or romantic overtures; a flirt or tease",
                                                "coracle " : "small rounded boat made of waterproof material stretched over a frame",
                                                "cordillera " : "group of mountain ranges forming a mountain system of great linear extent",
                                                "coriander " : "a type of aromatic herb, herb used in a variety of perfumes",
                                                "corinthian " : "pertaining to corinth or its culture, architectural term",
                                                "cortical " : "of, relating to, derived from, or consisting of cortex",
                                                "coruscate " : "sparkle; reflect brightly; shimmer",
                                                "cosmology " : "study of the physical universe considered a mass of phenomena in spacetime",
                                                "cosmopolitan " : "pertaining to the world at large, without localized prejudices",
                                                "coterie " : "tightly-knit group of persons having a common purpose or interest; cadre, clique",
                                                "craquelure " : "fine pattern of dense cracking formed on the surface of paintings",
                                                "crescendo " : "music, gradual increase of tempo, volume, or intensity",
                                                "crystal " : "mineral with many possible permutations; gemstone-like",
                                                "cumulonimbus " : "type of cloud that augurs, foretells, or indicates bad weather",
                                                "cuneiform " : "wedge-shaped; sumerian language",
                                                "curlicue " : "fancy curl or twist; flourish of writing",
                                                "cursive " : "flowing, effusive, wavy, type on handwriting in english",
                                                "curvilinear " : "consisting of or bound by curved lines; represented by a curved line",
                                                "cuvette " : "a small, transparent, often tubular laboratory vessel",
                                                "cyan " : "a type of greenish-blue",
                                                "cyaneous " : "a type of deep blue, cerulean",
                                                "cygnet " : "a baby swan; young swan",
                                                "cylinder " : "long, tubular geometric shape rendered in three dimensions",
                                                "cymbal " : "percussive instrument, usually attached to a drum kit",
                                                "cynophilist " : "dog-lover; one who loves or appreciates dogs",
                                                "cynosure " : "that which garners great attention by calling to its brilliance; interest",
                                                "cypress " : "type of swampy tree or plant, plant or tree occurring in swamps",
                                                "cytherean " : "pertaining to beauty or the goddess, aphrodite",
                                                "daedalian " : "intelligent; crafty; deft; practical; pertaining to daedalus",
                                                "dalliance " : "flirtation; dawdling; procrastination; frivolous action",
                                                "daphnean " : "shy; timid; demure; modest; bashful",
                                                "dapple " : "a spot or mottled marking, usually occurring in clusters; different tones and hues",
                                                "dawn " : "daybreak; first light of day; the onset of an idea; enlightenment",
                                                "decrescendo " : "gradual lowering of tempo in music or in a situation",
                                                "degringoladé " : "a rapid decline or deterioration, as in strength, position, or condition",
                                                "deign " : "to condescend to do something thought to be slightly beneath one's dignity",
                                                "delenda " : "that which needs to be deleted; something that has been deleted",
                                                "delineate " : "to describe, explain, or demonstrate",
                                                "deliquesce " : "to dissolve; transform into liquid from a solid",
                                                "delirium " : "state of mental disarray and unstable consciousness from intoxication or fever",
                                                "delitescent " : "hidden, concealed; kept secret",
                                                "dell " : "small, usually wooded valley; vale",
                                                "delphic " : "brotherly; oracular or prophetic",
                                                "demarche " : "course of action; maneuver; specific movement",
                                                "demesne " : "a lord’s privately owned manor or section of land",
                                                "demure " : "shy; modest; reserved in demeanor or behavior; having sedate reserve or sobriety",
                                                "denouement " : "final resolution or clarification of a dramatic or narrative plot",
                                                "desuetude " : "state of disuse; state of uselessness",
                                                "diablerie " : "dealing with the devil or devils; witchcraft; sorcery; consorting with demons",
                                                "diaphanous " : "light; delicate; gossamer; translucent",
                                                "diaspora " : "dissemination, dispersion; random or selective re-distribution",
                                                "dilettante " : "one who dabbles in an occupation or hobby without serious intent",
                                                "dioscuric " : "describing a twin, whether person or event, of a twin; of a duplicate",
                                                "dislodge " : "to remove or force out from a position or dwelling previously occupied",
                                                "dissemble " : "disguise or conceal one's true motives, feelings, or beliefs; to mislead",
                                                "dissimulate " : "to conceal or disguise; to hide with the intent of deceit",
                                                "divisi " : "music term, divided, separated",
                                                "dulcet " : "sweet-sounding; mellisonant",
                                                "dulciloquy " : "speech characterized by sounding soft or sweet",
                                                "dulcimer " : "stringed instrument having three or four strings and a fretted fingerboard",
                                                "dulcinea " : "sweetheart; lovely person; one whom a person loves or cares about",
                                                "dyslexia " : "disorder in which lexical figures are perceived in a chaotic order",
                                                "ebon " : "black; made of ebony",
                                                "echelon " : "tier; level; rank in job; formation of soldiers",
                                                "echo " : "a repetition of sound produced by the reflection of sound",
                                                "echolalia " : "immediate and involuntary repetition of words or phrases just spoken by others",
                                                "eclipsareon " : "a device for illustrating and demonstrating eclipses",
                                                "eclipse " : "any obscuration of light; reduction or loss of splendor, status, or reputation",
                                                "effervesce " : "to bubble over; to boil with frothy bubbles; to excite",
                                                "effleurage " : "a light, stroking movement used in massage; a soft caress",
                                                "effluvium " : "foul discharge or emanation; emission",
                                                "efflux " : "something that flows out or forth; effluence; passing or an expiration, as of time",
                                                "effulgent " : "marked by as if by brightly shining light; coruscating; shimmering",
                                                "effusive " : "gushing out or expressive; moving; cascading",
                                                "eglantine " : "a type of plant, european rose; sweetbrier",
                                                "eiderdown " : "the down of a duck used as stuffing for quilts or pillows",
                                                "eidolon " : "ghost, specter; reappearing; continuously visiting or persisting image",
                                                "élan " : "esprit; brio; gusto; ardor; vivacity",
                                                "elapse " : "to pass or go by; to happen",
                                                "elasticity " : "quality or state of being elastic; the tendency to keep shape after stretching",
                                                "elation " : "quality or state of being elated; feeling or state of great joy or pride",
                                                "eleemosynary " : "of, relating to, or dependent on charity; contributed as an act of charity",
                                                "element " : "fundamental, essential, or irreducible constituent of a composite entity",
                                                "eleven " : "the eleventh integer in a series, “11”",
                                                "elicit " : "to bring or draw out (something latent); educe; summon; to provoke a reaction",
                                                "elision " : "omission of a vowel, consonant, or syllable in pronunciation",
                                                "elixir " : "solution of alcohol and water; substance believed to maintain life indefinitely",
                                                "ellipsis " : "omission of a word or phrase necessary for a complete syntactical construction",
                                                "elliptical " : "of, relating to, or having the shape of an ellipse; with a word or words omitted",
                                                "eloign " : "to move away a distance; to move a distance with something concealed",
                                                "eloquence " : "well-stated speech; flowing language; articulated speech and proper execution",
                                                "elucidate " : "to explain further; clarify; to elaborate upon",
                                                "elusive " : "difficult to find, catch, or achieve; avoiding or having a tendency to avoid or evade",
                                                "elysian " : "blissful, delightful; pertaining to the elysian fields or elysium",
                                                "elysium " : "a section of the underworld, the resting place of heroes and the virtuous",
                                                "emaciate " : "to make abnormally thin or weak, typically due to illness",
                                                "emanation " : "emission; something that is issued by a source",
                                                "embarcadero " : "a landing place, especially a landing place on an island waterway",
                                                "ember " : "small, glowing fleck of burning wood or coal",
                                                "emerald " : "deep, dark green; dark green gemstone",
                                                "emissary " : "an agent sent on a mission to represent or advance the interests of another",
                                                "emission " : "discharge; emanation; chemical release",
                                                "emollient " : "substance that softens and soothes the skin; lotion",
                                                "empyreal " : "related to the empyrean; celestial",
                                                "emulate " : "to strive to equal or excel, especially through imitation",
                                                "emulsify " : "to pour liquid into another non-soluble; creating visible density",
                                                "enamel " : "vitreous, usually opaque, protective or decorative coating or shell",
                                                "enceinte " : "pregnant, carrying a baby, gravid; line of fortification enclosing a town or castle",
                                                "encomium " : "formal, enthusiastic praise; abundant, exuberant expression of admiration",
                                                "enhalo " : "to affix with a halo; to cause to wear a halo; to encircle; surround",
                                                "ennui " : "listlessness; weariness; discontent",
                                                "ensconce " : "establish or settle in a safe, secure, or comfy place",
                                                "epée " : "fencing sword or blade without a cutting edge",
                                                "epergne " : "table centerpiece; object designated as a centerpiece",
                                                "ephebe " : "young man; swain, young suitor",
                                                "ephemeral " : "brief; transient; evanescent",
                                                "epicede " : "dirge, requiem; funeral song or ode",
                                                "epicurean " : "hedonistic; gastronomical; pertaining to good taste",
                                                "epigone " : "inferior imitator; disciple; second-rate replica; counterfeit",
                                                "epileptic " : "pertaining to epilepsy; flickering rapidly; seizing",
                                                "epiphany " : "revelation of thought, typically conceived after an eventful experience",
                                                "epistle " : "a formal letter; a letter with a cachet",
                                                "epitaph " : "an inscription on a tombstone",
                                                "epithelium " : "a type of body tissue",
                                                "epitome " : "a perfect example of a particular quality or type",
                                                "equestrian " : "of, relating to, or featuring horseback riding",
                                                "equinox " : "an annual event wherein after the sun reaches a height, night and day occur simultaneously",
                                                "equipoise " : "equal distribution of weight or balance; balanced",
                                                "eristic " : "characterized by disputatious, often subtle and specious reasoning",
                                                "escadrille " : "a small squadron, usually of six; a small team, typically of six airplanes",
                                                "escalade " : "the act of scaling a wall, usually with a ladder or rope",
                                                "escamotage " : "juggling; hand trickery; sleight of hand; legerdemain",
                                                "escarole " : "type of green chicory",
                                                "esclavage " : "a necklace having several rows of chains, beads, or jewels",
                                                "escritoire " : "writing desk; desk designed for studies",
                                                "esculent " : "edible; able or safe to be eaten",
                                                "esoterica " : "item or thing that is esoteric, obscure, rare, or valuable",
                                                "esper " : "a being of advanced mentality or with psychic abilities",
                                                "esprit " : "brio; wit; vivacity; joie de vivre",
                                                "essence " : "intrinsic or indispensable properties that serve to typify or identify something",
                                                "esssse " : "pl. archaic plural of ashes",
                                                "estuary " : "inlet or arm of the sea; an open river that connects to the sea",
                                                "esurient " : "hungry; greedy; hedonistic in pursuit of things",
                                                "ethereal " : "heavenly; airy in substance; spectral; insubstantial and light",
                                                "etiolate " : "to stunt growth; to deprive of strength; to whiten by blocking sunlight exposure",
                                                "etude " : "a piece of music designed for didactic purposes",
                                                "eunoia " : "normal mental health; beautiful thinking",
                                                "euphonious " : "nice-sounding; sounding pretty",
                                                "euphoria " : "feeling of great happiness or well-being; felicity",
                                                "evanescent " : "brief; transient; ephemeral",
                                                "evaporation " : "the act of liquid dissipating or drying due to humidity or exposure",
                                                "eviscerate " : "to disembowel; exenterate; to remove the viscera of something",
                                                "evocative " : "that which evokes; something that reminds, inspires, or impresses",
                                                "excelsior " : "fine, curled wood shavings",
                                                "exclusion " : "the act of excluding; the act of shutting out or preventing entrance",
                                                "existential " : "of, relating to, or dealing with existence; pertaining to existentialism",
                                                "expatiate " : "to speak or write at length or in considerable detail; expound, elaborate",
                                                "exuviate " : "to shed a shell; molt; unsheathe",
                                                "façade " : "affected aura or mannerisms to beguile or deceive",
                                                "facility " : "building made or used for convenience; ease of moving or doing; aptitude",
                                                "facsimile " : "copy or reproduction of an item, typically a book",
                                                "fainéant " : "sluggard; do-nothing; ne’er-do-well; idle and ineffectual",
                                                "falciform " : "falcate; curved; convex; sickle-shaped",
                                                "famished " : "extremely hungry; ravenous; starved",
                                                "famulus " : "sorcerer’s apprentice or assistant",
                                                "felicity " : "state of happiness; joy; ecstasy",
                                                "fissure " : "long narrow opening; a crack or cleft; process of splitting or separating; division",
                                                "fleur-de-lys " : "stylized insignia of a lily",
                                                "foliage " : "plant leaves or greenery, as a collective",
                                                "formulaic " : "being of no special quality or type; average; routine; undistinguished",
                                                "forte " : "niche in which a person excels",
                                                "foudroyant " : "dazzling; scintillating; sudden and overwhelming",
                                                "frescade " : "a cool, breezy walk; a shady place; a relaxing place with ample shade",
                                                "frolic " : "to behave playfully and candidly; romp; to engage in flirting, joking, or teasing",
                                                "frost " : "hoarfrost; degree or state of coldness; covering of minute ice needles",
                                                "fuchsia " : "bright pinkish-purple",
                                                "fuliginous " : "having the color of soot; dark; dusky; charcoal-colored",
                                                "fumarole " : "hole in an area of volcanic activity from which gases and hot smoke escape",
                                                "fumulus " : "a thin cloud resembling a veil and forming at any level",
                                                "furrow " : "to wrinkle; a wrinkle, a rut, groove, or trench",
                                                "fuselage " : "central body of an aircraft, to which the wings and tail assembly are attached",
                                                "fusillade " : "salvo; rapid discharge of firearms",
                                                "galaxy " : "collection of stars, gas, and dust bound together by gravity",
                                                "gale " : "a harsh gust of wind; a strong current of wind",
                                                "galleria " : "spacious passageway, court, or indoor mall, usually with a vaulted roof; gallery",
                                                "gallery " : "raised area, often having a stepped or sloping floor, in a public building",
                                                "gambol " : "to skip or jump merrily",
                                                "gaucherie " : "awkwardness; inexperience; embarrassments",
                                                "girandole " : "a mirror having attached candle holders",
                                                "glacial " : "slow; staggering; of or pertaining to glaciers or ice sheets",
                                                "glimpse " : "brief, incomplete view or look; to glance at",
                                                "glisten " : "to shine by reflection with a sparkling luster; coruscate; shimmer",
                                                "gloaming " : "dusk, twilight, evening, vesper",
                                                "gloom " : "sadness; melancholy; depression",
                                                "glyph " : "a sigil or specific insignia; a letter of language; an arcane mark",
                                                "gossamer " : "delicate; light; flimsy; transparent and thin, like a spider’s silk",
                                                "gracile " : "gracefully slender or thin; graceful",
                                                "grandeur " : "splendor; magnificence; quality or state of being grand",
                                                "grazioso " : "a direction in music, graceful, smooth, or elegant in style",
                                                "hacienda " : "the main building of a farm or ranch",
                                                "halcyon " : "legendary kingfisher; tranquil, calm, without strife, serene",
                                                "hallucinate " : "to affect or be affected with visions or imaginary perceptions",
                                                "hazel " : "light brown or light yellow",
                                                "heath " : "plain tract of wasteland; uncultivated land",
                                                "hegemony " : "predominant influence; dominance, supremacy, preeminence",
                                                "heliotrope " : "a type of purple flower; a light purple",
                                                "helix " : "a spiral; spiral-shaped object or string",
                                                "henna " : "reddish-brown dye used in tinting the hair, skin, or nails",
                                                "hubris " : "excessive pride; overbearing arrogance",
                                                "hue " : "gradation or variety of a color",
                                                "humiliate " : "to enervate or embarrass through specific actions or events",
                                                "hyacinth " : "tropical, american herb; red, transparent variety of zircon used as a gemstone",
                                                "icicle " : "a sliver of tapered, frozen water, usually hanging from something",
                                                "idyllic " : "like an idyll; extremely happy, peaceful, or picturesque",
                                                "ilium " : "upper part of the bony femur at the hip joint",
                                                "illusion " : "erroneous mental representation; false image made by outside force or the mind",
                                                "illusory " : "produced by, based on, or having the nature of an illusion; deceptive",
                                                "illustrate " : "to clarify or explain with examples or comparisons",
                                                "imbroglio " : "extremely confused, complicated, or embarrassing situation",
                                                "imbue " : "to embed with a quality, to inspire or permeate with a feeling or quality",
                                                "immaculate " : "spotless; free of sin; without blemish or impurity",
                                                "immure " : "to enclose with walls; ensconce",
                                                "impedimenta " : "pl. things that hinder growth or movement",
                                                "impetus " : "a drive or compelling force; motivation; a reason to do something",
                                                "impluvium " : "of a roman house, rectangular pool in an atrium used to gather rain water",
                                                "imprimatur " : "a sign or mark of approval; insignia of approval",
                                                "incalescent " : "becoming hotter or growing more ardent; boiling",
                                                "incarnadine " : "pinkish; flesh-colored; blood-red",
                                                "incense " : "to induce rage; infuriate; aromatic element designed to induce relaxation",
                                                "incipient " : "in or at an initial stage; beginning to exist or appear",
                                                "incisive " : "penetrating; clear, and sharp, as in operation or expression",
                                                "incunabula " : "pl. book printed before 1501",
                                                "indolence " : "laziness; extreme ease or comfort",
                                                "ineffable " : "indescribable; impossible to describe; enchantingly amazing",
                                                "inertia " : "tendency of a body to resist acceleration, “a body at rest wants to stay at rest”",
                                                "influenza " : "acute contagious viral infection, commonly called the “flu”",
                                                "ingénue " : "a naive, innocent girl or young woman",
                                                "inglenook " : "a nook or corner beside an open fireplace; chimney corner",
                                                "ingravescent " : "gradually becoming more severe; worsening, usually of a medical condition",
                                                "innocent " : "without sin; pure, free from legal or specific wrong; guiltless; naïve; simple",
                                                "inoccuity " : "the quality or state of being harmless, trifling, or insipid",
                                                "inoculate " : "introduce an idea or view into the mind of; to inculcate; to inject a serum or vaccine",
                                                "insipid " : "lacking flavor or zest; lacking excitement, stimulation, or interest; dull; vapid",
                                                "intaglio " : "an engraving or incised figure in stone or other hard material",
                                                "inundate " : "deluge; to fill quickly beyond capacity; to cover with water; drench; overwhelm",
                                                "inure " : "to take effect or to become accustomed to something, typically unpleasant",
                                                "iris " : "the colored portion of the eye that encircles the pupil",
                                                "iscariotic " : "traitorous; treacherous; given to betrayal; having committed betrayal",
                                                "isinglass " : "thin sheet(s) of translucent mica",
                                                "isosceles " : "of a triangle, having two equal sides",
                                                "isthmus " : "narrow strip of land connecting two larger masses of land",
                                                "ivory " : "pure white color; material derived from elephant tusks",
                                                "jacqueminot " : "a type of flower, a crimson rose",
                                                "jaunt " : "short excursion for pleasure; brief stay",
                                                "jejune " : "naïve; juvenile; simplistic; uninteresting; superficial",
                                                "juxtapose " : "to place side by side, especially for comparison or contrast",
                                                "kaleidoscope " : "optical item that utilizes mirrors to create interior symmetrical visions",
                                                "kismet " : "fate; fortune; chance; faith in fate, chance, or fortune",
                                                "knell " : "to ring slowly and solemnly; funeral bell-ring",
                                                "l’esprit de l’escalier " : "“staircase wit”, the usage of a witty retort after the moment has passed",
                                                "labial " : "pertaining to, of, or utilizing the lips",
                                                "labyrinth " : "maze; puzzling complex or circuitous plan",
                                                "lacerate " : "to cut or tear irregularly; to distress; mangle",
                                                "laconic " : "brief in speech; matter-of-fact; terse, using few words",
                                                "lacquer " : "varnish that dries via evaporation",
                                                "lacuna " : "omission or empty space; gap in chronology",
                                                "lagniappe " : "gift for extended patronage; gift or compensation for valued customers",
                                                "lambent " : "glowing, gleaming, or flickering with a soft radiance",
                                                "laminate " : "to beat or compress into a thin plate or sheet; to divide into thin layers",
                                                "languid " : "characterized by disinclination for physical exertion",
                                                "laodicean " : "indifferent or lukewarm in politics and or religion",
                                                "lapis lazuli " : "a gemstone of intense blue",
                                                "largesse " : "the generous giving of gifts; a generous or courteous gift; charitable donation",
                                                "lascivious " : "lewd, lustful, prurient",
                                                "lassitude " : "weariness; lack of energy or motivation",
                                                "lathe " : "machine for shaping a piece of material by rotating it rapidly along its axis",
                                                "lattice " : "open framework of material, typically in a crisscross pattern",
                                                "lavadero " : "a laundry room; a place designated for washing gold",
                                                "lavender " : "a type of light purple; a type of flower; an oft perfumed scent",
                                                "lavish " : "expended, bestowed, or occurring in large amounts; using or giving in great amounts",
                                                "layer " : "single thickness of a material covering a surface",
                                                "legerity " : "mental or physical agility, dexterity, or quickness",
                                                "leitmotif " : "musical passage associated to a specific situation, character, or idea",
                                                "lemniscate " : "the infinity symbol; any figure-eight symbol",
                                                "lemonade " : "beverage typically consisting of lemon juice, sugar, and water",
                                                "lesbian " : "female sexually attracted to other women, exclusively",
                                                "lethe " : "the condition of forgetfulness; oblivion",
                                                "leveret " : "baby rabbit; a young rabbit",
                                                "leviathan " : "very large animal, especially a whale; something of unusually large size",
                                                "levitation " : "the act of floating; supernatural floating",
                                                "lexiphanes " : "pretentious word user; bombastic or magniloquent person",
                                                "liaison " : "illicit sexual relationship; case of contact between two parties, usually a person",
                                                "libeccio " : "southwest wind occurring in italy",
                                                "lilliputian " : "very small, tiny; pertaining to lilliput",
                                                "lilt " : "cadence of voice; rhythm of language or sentences; good vocal or musical structure",
                                                "limerence " : "extended infatuation or crush, contrast love",
                                                "limn " : "to delineate via depictions or suffuse things with light",
                                                "limousine " : "slender car used for formal occasions, notably expensive",
                                                "limpid " : "unclouded; clear; lucid; defined and deep",
                                                "lineaments " : "pl. the distinguishing or characteristic features of something immaterial",
                                                "linguistics " : "pl. the study of human speech, languages, and writing",
                                                "linoleum " : "a type of floor covering",
                                                "liquid " : "a state of matter, compare gas and solid; readiness to flow; a type of sound",
                                                "lissom " : "supple; easily bent; lithe; flexible",
                                                "listless " : "lacking energy or disinclined to exert effort; lethargic",
                                                "litany " : "large amount; plethora; long and tedious address or recital",
                                                "literati " : "intelligentsia; the educated class; clerisy; a group of litterateurs",
                                                "lithe " : "readily bent; supple; flexible; marked by effortless grace",
                                                "lithium " : "silvery, soft, and highly-reactive metal",
                                                "lithosphere " : "outermost shell of a planet; the crust and uppermost mantle",
                                                "litote " : "rhetorical term, a specific type of understatement",
                                                "litterateur " : "literary-minded person; one devoted to the study or writing of literature",
                                                "lixiviation " : "the act of separating soluble from insoluble substances via water or a solvent",
                                                "lochetic " : "lying in wait for prey, used especially of insects",
                                                "loom " : "the art of weaving; to come into view as a massive, distorted, or indistinct image",
                                                "loquacious " : "characterized by talking; talking freely or too much; excessively talkative",
                                                "lorgnette " : "a pair of eyeglasses or opera glasses with a handle",
                                                "lubricious " : "slippery with oil or lubricant; offensively lewd or intending to be lewd",
                                                "lucent " : "shining; gleaming brilliantly",
                                                "lugubrious " : "gloomy or dismal, especially exaggerated",
                                                "lullaby " : "song or tune devised to lull something to sleep",
                                                "luminal " : "of or pertaining to the lumen (the measure of light perceived by the human eye)",
                                                "luminary " : "one who is an inspiration to others; one who attained success in a chosen field",
                                                "lunacy " : "insanity; insanity with brief moments of clarity",
                                                "lunula " : "white crescent at the base of the fingernail",
                                                "luscious " : "delicious; sexy; cloying; alluring",
                                                "lustrous " : "having noticeable or vivid luster and sheen",
                                                "macedoiné " : "mixture of diced fruits and vegetables; medley; mixture",
                                                "magisterial " : "of, relating to, or having the features of a master or teacher; authoritative",
                                                "malady " : "sickness, illness; ague; ictus; ailment",
                                                "malaise " : "bodily weakness; nondescript illness; vague feeling of discomfort",
                                                "malapropos " : "out of place; inappropriate; in an inopportune or inappropriate manner",
                                                "malleable " : "moldable; able to be modified; easily reshaped; having the ease of form",
                                                "mannequin " : "articulated human figure used for design",
                                                "mantelletta " : "sleeveless vestment worn by cardinals",
                                                "maquette " : "scale model of a large item",
                                                "maraschino " : "cordial made from the fermented juice of the marasca cherry",
                                                "marasmus " : "a type of protein deficiency; state of emaciation",
                                                "marble " : "highly-polished building material; irregularly colored",
                                                "marcescent " : "flower term, withering, but not falling off",
                                                "marginalia " : "notes in the margin or margins of a book",
                                                "marionette " : "a puppet bound by strings and controlled with wooden bars",
                                                "marmalade " : "jellylike preserve made from the pulp of fruits, especially citrus fruits",
                                                "marmoreal " : "of, like, made of, or related to marble",
                                                "masquerade " : "festive gathering characterized by participants wearing masks",
                                                "material " : "secular; worldly; the substance(s) of which a thing is made of or composed",
                                                "matriculate " : "to become admitted to membership in a body, society, or institution",
                                                "matutinal " : "of, relating to, or occurring in the morning; early",
                                                "maudlin " : "overly sentimental; saccharine; mawkish; self-pitying",
                                                "mausoleum " : "large, stately tomb or building housing several tombs",
                                                "mauve " : "a type of pinkish purple",
                                                "medallion " : "jewelry or object worn from a necklace",
                                                "medley " : "heterogeneous mixture of typically complementing elements",
                                                "melisma " : "the stretching of a syllable over a series of notes",
                                                "mellifluous " : "flowing with sweetness or honey; smooth and sweet, often of a sound or voice",
                                                "mellisonant " : "wonderful-sounding; pleasant-sounding",
                                                "melody " : "a series or pattern of notes",
                                                "memento " : "an item of special significance, usually as a token of remembrance",
                                                "memorabilia " : "pl. things remarkable and worthy of remembrance or record",
                                                "menagerie " : "collection of animals in cages or enclosures; diverse hodgepodge; gallery; zoo",
                                                "mephitic " : "poisonous; noxious; lethally dangerous; insidious; toxic; putrid",
                                                "mercurial " : "fickle; erratic; ingenious; changeable; eloquent",
                                                "mere " : "being nothing more nor better than; small; lowly",
                                                "meretricious " : "drawing attention in a vulgar manner; gaudy, tawdry; superficially attractive",
                                                "meridian " : "of or at noon; imaginary line that extends from the north to south poles",
                                                "mestizo " : "a person of mixed racial ancestry",
                                                "métier " : "forte; niche in which a person excels; occupation; profession",
                                                "mewl " : "whimper; cry like an infant; meow like a kitten; to weakly cry",
                                                "mezzanine " : "partial story between two main stories of a building; lowest balcony of theater",
                                                "miasma " : "an atmosphere of disease; fine mist of effluvium or bacteria; noxious emanation",
                                                "mica " : "thin layers of specific, transparent minerals",
                                                "midst " : "in the middle of; among",
                                                "mien " : "air or bearing especially as expressive of attitude or personality; demeanor; aura",
                                                "milieu " : "surroundings or environment, especially of a social or cultural nature",
                                                "millennium " : "one thousand years; period of a thousand years",
                                                "milquetoast " : "timid, unassertive, spineless person; one who is easily intimidated",
                                                "mimesis " : "imitation or representation of the world, mostly in literature and art; mimicry",
                                                "mimosa " : "a type of plant; a cocktail drink",
                                                "mimsy " : "flimsy and miserable; someone who excels at what they do",
                                                "miniscule " : "very small; diminutive, when compared to a normal counterpart",
                                                "minutiae " : "pl, tiny, precise details; vestiges; trifles",
                                                "mirror " : "surface able of reflect enough undiffused light to form an image of an object",
                                                "miscellany " : "collection of various items, parts, or ingredients",
                                                "mist " : "mass of fine droplets of liquid",
                                                "mithril " : "a fictional, very light, and silvery steel",
                                                "mizzenmast " : "third mast or the mast aft the mainmast on a ship having three or more masts",
                                                "mizzle " : "fine rainfall; drizzle; mist",
                                                "moiety " : "one of two equal parts; half",
                                                "morceau " : "a small literary or musical composition",
                                                "mormorando " : "musical direction, murmuring or with a murmuring sound",
                                                "moue " : "pouting face or grimace; upset facial expression",
                                                "murmur " : "low, indistinct, and continuous sound; to utter such a sound",
                                                "myriad " : "multitude; litany; an amount of, usually large; collection in large numbers",
                                                "myrrh " : "fragrant resin gum from a type of tree, used chiefly for perfume",
                                                "mystique " : "the special, esoteric skill or mysterious faculty essential in a calling or activity",
                                                "mythopoeic " : "pertaining to the making of myths",
                                                "nacreous " : "iridescent; pearly; like mother-of-pearl or nacre",
                                                "naiad " : "a nymph; a river, lake, fountain, or spring nymph or spirit",
                                                "naïveté " : "inexperience; quality of being naïve; artlessness",
                                                "nebulae " : "pl. a collection of astral gases",
                                                "nemesis " : "source of harm or ruin; unconquerable foe or enemy; vengeful opponent",
                                                "nenuphar " : "a water lily, especially an egyptian lotus",
                                                "neophyte " : "a novice; tyro; beginner",
                                                "nepenthe " : "drug of forgetfulness; anti-depression drug; remedy for sorrow",
                                                "nepheliad " : "cloud nymph; nymph designated or of the clouds",
                                                "nephew " : "the son of a brother or sister in relation to you",
                                                "nickelodeon " : "a theater that charges a nickel (5 cents) for entry",
                                                "nimbus " : "dark, grey cloud bearing rain; splendid atmosphere or aura; cloudy radiance",
                                                "nimiety " : "excess, overabundance, superfluity",
                                                "nirvana " : "a place or state of rest, harmony, or pleasure",
                                                "niveous " : "snowy or resembling snow; like, of, relating to, or made of snow",
                                                "nocive " : "harmful, injurious, or causing pain",
                                                "noctilucence " : "cloud phenomenon typified by lights at night, being visible or glowing at night",
                                                "nonchalant " : "feeling or appearing casually calm and relaxed; indifferent",
                                                "novae " : "pl. collapsing or dying stars",
                                                "novella " : "short prose tale often characterized by moral teaching or satire",
                                                "novitiate " : "novice; the living place of a novice; the state of being a novice; neophyte",
                                                "nucleus " : "central part about which other parts are grouped or gathered",
                                                "nugacious " : "trifling, trivial; insignificant; unimportant; worthless",
                                                "nullibicity " : "state of non-existence; quality or state of being nowhere",
                                                "nullifidian " : "a person having no faith, religion, convictions, or beliefs",
                                                "numeral " : "symbol used to represent, denote, or symbolize a number",
                                                "numina " : "pl. presiding divinities or spirits of a place; creative energies",
                                                "numismatics " : "study or collection or currency, coins, paper money, etc.",
                                                "nymph " : "seductive or lustful woman; fairy",
                                                "nymphet " : "pubescent girl regarded as sexually desirable; young, sexually precocious girl",
                                                "oasis " : "fertile, vibrant, or green spot in a desert or wasteland",
                                                "objet d’art " : "object of art; valuable or highly artistic piece or work",
                                                "oblivion " : "condition or quality of being completely forgotten; void; forgetfulness",
                                                "obsequious " : "fawning, sycophantic, servile",
                                                "obsidian " : "volcanic glass of a black shade",
                                                "ocelot " : "undomesticated cat, akin to a small leopard",
                                                "odalisque " : "female servant; female servant in a harem",
                                                "oeillade " : "an amorous glance; ogle",
                                                "oeuvre " : "the corpus of an author, canon, or a collective symposium",
                                                "oleander " : "a type of flower",
                                                "opacity " : "opaqueness; obscurity; impenetrability",
                                                "opalescent " : "milky and iridescent; shimmering with the colors of an opal",
                                                "opaque " : "impenetrable to light; not reflecting light; difficult to explain or understand",
                                                "ophidian " : "snake-like; like, shaped like, or relating to snakes",
                                                "opulence " : "wealth, affluence; great abundance; profusion; pretentiousness",
                                                "opusculum " : "a minor work of literature",
                                                "orbital " : "of, pertaining to, or relating to an orbit",
                                                "orchestra " : "large group of musicians with a variety of instruments",
                                                "oscillate " : "to swing or move in an uninterrupted motion",
                                                "ossuary " : "place, container, or receptacle for holding the bones of the dead",
                                                "otiose " : "indolent; lazy; serving no useful purpose; futile; being a leisure",
                                                "oubliette " : "dungeon with only opening at the top",
                                                "palatial " : "pertaining to a palace; grandiose; magnificent",
                                                "palaver " : "conference or discussion; idle chat; chat with flattery of cajolery involved",
                                                "palisade " : "a fence of pales or stakes set firmly in the ground",
                                                "palladian " : "of or relating to wisdom or learning",
                                                "palliasse " : "mattress consisting of a thin pad filled with straw, sawdust, or hay",
                                                "palliate " : "to alleviate, reduce, or remove pain",
                                                "pallid " : "pale, wan, or deficient in color",
                                                "panacea " : "a cure-all; medicine, herb, or concoction designed or functioning as a cure-all",
                                                "panoply " : "a full collection or array; full set of armor",
                                                "panoramic " : "unbroken view of an entire surrounding area; inclusive presentation; survey",
                                                "pantomime " : "communication through gestures and facial movements",
                                                "paradigm " : "clearly defined archetype; typical example or pattern of something",
                                                "paramour " : "lover, especially one in an adulterous relationship; lover; illicit lover",
                                                "paraph " : "a flourish at the end of a signature, may be used as a safeguard against forgery",
                                                "paroxysm " : "a sudden attack, convulsion, or seizure, usually of an emotional or medical nature",
                                                "parvenu " : "noveau-riche; person having risen to new status, but lacks the social skills necessary for it",
                                                "pasquinade " : "public farce, satire, or lampoon",
                                                "pastiche " : "literary patchwork, hodgepodge; collision of genres used to create a new item",
                                                "patina " : "natural tarnish from wear of usage and passage of time; verdigris",
                                                "patois " : "dialect other than the usual or literary dialect; uneducated or provincial language",
                                                "paucity " : "scarcity; lack of presence; fewness; a small number",
                                                "peccadillo " : "insignificant sin or wrongdoing; trifling fault",
                                                "peccavi " : "admission of guilt; confession",
                                                "pellucid " : "translucently clear, limpid, or ethereal",
                                                "peninsula " : "piece of land mostly surrounded by water, except on one side",
                                                "pensive " : "brooding; reflecting, involving, or engaged in deep or serious thought",
                                                "penumbra " : "a partial shadow; space of partial illumination; the limits of a shadow",
                                                "percolate " : "to filter; to cause to filter; to cause to pass through pores or small holes",
                                                "perennial " : "lasting throughout the year, typically of a plant",
                                                "perforate " : "to pierce, punch, or bore a hole or holes in; stab through; penetrate",
                                                "periphery " : "line that forms the boundary; limited circumference of sight; perimeter",
                                                "permeate " : "to pervade, to spread, or flow throughout; to diffuse through",
                                                "perpetuity " : "the quality or condition of being perpetual, ceaseless, or continual",
                                                "phantasm " : "something apparently seen but having no physical reality; illusion",
                                                "philander " : "to womanize or entertain or elicit casual or wanton sex",
                                                "philanthropy " : "the effort or drive to further the well-being of humankind; generosity",
                                                "philosophy " : "discipline comprising aesthetics, ethics, metaphysics, and epistemology, etc.",
                                                "philtrum " : "subtle curve beneath the nose and on the upper lip",
                                                "phoenix " : "mythical bird of fire which rises from its ashes in a cycle of rebirth",
                                                "pianissimo " : "musical direction, very softly",
                                                "piquant " : "aromatic, appetizing, or appealingly provocative",
                                                "pirouette " : "ballet spin, ballet technique",
                                                "pizzicato " : "music term, played by plucking rather than bowing",
                                                "placid " : "sedate, calm, peaceful, relaxed, serene",
                                                "plumage " : "entire feathery covering or portion of a bird; feathers collectively",
                                                "pluvial " : "characterized or relating to rainfall",
                                                "pococurante " : "nonchalant, indifferent lukewarm in opinion; insouciant",
                                                "poignant " : "profoundly moving; touching; physically or emotionally painful",
                                                "ponceau " : "a strong red to reddish orange",
                                                "porcelain " : "strong, vitreous, and translucent ceramic with glazed colored material",
                                                "portfolio " : "portable case for carrying documents",
                                                "portico " : "porch or walkway with a roof supported by columns, often leads into an entrance",
                                                "portmanteau " : "large suitcase; merging of two words to form a new one, often a pun",
                                                "prairillon " : "a small meadow or tract of grassland; heath; plain",
                                                "precocious " : "manifesting or characterized by unusually early development or maturity",
                                                "prelude " : "preceding event or action; music term, preliminary",
                                                "preterlabent " : "flowing beside or by, especially of a river or stream",
                                                "prismatic " : "refractive light of a spectrum; brilliantly colored",
                                                "pristine " : "in primordial condition; untouched; belonging to the earliest period or state",
                                                "promethean " : "boldly creative, defiantly original, deviating genius",
                                                "propinquity " : "nearness in place; approximate location; proximity; vicinity",
                                                "proscenium " : "greek or roman theater stage, the part of a stage in front of the curtain",
                                                "prosody " : "the rhythm, stress, and intonation of speech",
                                                "provocative " : "tending or serving to provoke; inciting, stimulating, irritating, or vexing",
                                                "prurient " : "having, relating to, or typified by lascivious or lustful thoughts or desires",
                                                "psithurisma " : "whisper; sound of wind through the trees; sound of wind-rustled leaves",
                                                "psittacism " : "automatic speech without thought of the meaning of the words spoken",
                                                "psyche " : "the mind or self as a functional entity; the center of thought, feeling, and motivation",
                                                "punchinello " : "short, fat clown or clown puppet",
                                                "puree " : "rub through a strainer or process in an electric blender",
                                                "purlicue " : "space between the thumb and forefinger",
                                                "pyrrhic " : "of a victory, having high levels of casualties or damage on both sides",
                                                "quaquaversal " : "directed outward from a common center to all points; omnidirectional",
                                                "querencia " : "the area of the bull-ring where the bull makes its stand",
                                                "quintessence " : "fifth element; perfect embodiment",
                                                "quisquose " : "something which is difficult to deal with",
                                                "quiver " : "shiver; shake; quaver; tremble",
                                                "quotidian " : "daily; mundane; occurring every day",
                                                "radii " : "pl. any line segments from the center of a circle or sphere to its perimeter",]
}

extension ModelWords {
    func addMe() {
        ModelWords.prettyWords.forEach { w in
            F.addWord(WordModel(word: w.key, type: WordType.unknown, translation: w.value, createdDate: Date()))
        }
    }
}
